name: mongodb
version: 4.0.0
description: MongoDB v4.0 - easy and fast installing database unit. "Better done yourself" chart :)
maintainers:
- name: Alexey Chuprin
email: maddogsstyle@gmail.com
appVersion: 4.0
