apiVersion: v1
kind: Pod
metadata:
  labels:
    crawler: aux
spec:
  containers:
    - name: docker
      image: docker:20.10.18
      command:
        - cat
      tty: true
      privileged: true
      volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
  volumes:
    - name: dockersock
      hostPath:
        path: /var/run/docker.sock
