---
dependencies:

  - name: ingress-nginx
    version: "4.3.0"
    repository: https://kubernetes.github.io/ingress-nginx

  - name: crawler
    version: "1.0.0"
    repository: "file://../crawler"

  - name: ui
    version: "1.0.0"
    repository: "file://../ui"

  - name: mongodb
    version: "13.4.1"
    repository: https://charts.bitnami.com/bitnami

  - name: prometheus-mongodb-exporter 
    version: "3.1.2"
    repository: https://prometheus-community.github.io/helm-charts

  - name: rabbitmq
    version: "11.1.1"
    repository: https://charts.bitnami.com/bitnami

  - name: prometheus-rabbitmq-exporter
    version: "1.3.0"
    repository: https://prometheus-community.github.io/helm-charts

