apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  definition.json: |-
    {
      "rabbit_version": "3.11.7",
      "rabbitmq_version": "3.11.7",
      "product_name": "RabbitMQ",
      "product_version": "3.11.7",
      "users": [
        {
          "name": "guest",
          "password_hash": "1mQhewiipnunyOpcuL6LITAwivR0Y+oBJoAGRFs+iS3BEzVN",
          "hashing_algorithm": "rabbit_password_hashing_sha256",
          "tags": [
            "administrator"
          ],
          "limits": {}
        }
      ],
      "vhosts": [
        {
          "name": "/"
        }
      ],
      "permissions": [
        {
          "user": "guest",
          "vhost": "/",
          "configure": ".*",
          "write": ".*",
          "read": ".*"
        }
      ],
      "topic_permissions": [],
      "parameters": [],
      "global_parameters": [
        {
          "name": "internal_cluster_id",
          "value": "rabbitmq-cluster-id-qgHKVmiw8_-mcxo4rD73Pg"
        }
      ],
      "policies": [],
      "queues": [
        {
          "name": "mqqueue",
          "vhost": "/",
          "durable": false,
          "auto_delete": false,
          "arguments": {}
        }
      ],
      "exchanges": [],
      "bindings": []
    }