---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "backend.fullname" . }}
  labels:
    app: crawler
    component: backend
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: crawler
      component: backend
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: crawler
        component: backend
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: backend
        env:
        - name: MONGO
          value: mongodb.default.svc.cluster.local #internal ip монги
        - name: MONGO_PORT
          value: "27017"
        - name: RMQ_HOST
          value: project-rabbitmq.default.svc.cluster.local #internal ip сервиса RMQ
        - name: RMQ_QUEUE
          value: mqqueue
        - name: RMQ_USERNAME
          value: user
        - name: RMQ_PASSWORD
          value: pass
        - name: CHECK_INTERVAL
          value: "60"
        - name: EXCLUDE_URLS
          value: .*github.com