---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "rabbitmq-exporter.fullname" . }}
  labels:
    app: crawler
    component: rabbitmq-exporter
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: rabbitmq-exporter
      release: {{ .Release.Name }}
  template:
    metadata:
      name: rabbitmq-exporter
      labels:
        app: crawler
        component: rabbitmq-exporter
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: kbudde/rabbitmq-exporter
        name: rabbitmq-exporter
        env:
        - name: RABBIT_URL
          value: http://rabbitmq:5672
        - name: RABBIT_USER
          value: user
        - name: RABBIT_PASSWORD
          value: password
        - name: INCLUDE_QUEUES
          value: queue1