mongodb:
  auth:
    enabled: false

rabbitmq:
  authentication:
    erlangCookie: "/var/lib/rabbitmq/.erlang.cookie"
  customConfig: management.load_definitions = /rabbitmq-secret/definition.json #Подбрасываем настройки для очереди по умолчанию...
  extraSecrets: #...через заранее созданный секрет
    - name: rabbitmq-secret
      mountPath: /rabbitmq-secret

kube-prometheus-stack:
  grafana:
    service:
      port: 8880
  prometheus:
    prometheusSpec:
       additionalScrapeConfigs:
        - job_name: 'crawler'
          static_configs:
          - targets: ['project-crawler.svc.cluster.local:8000'] #ClusterIP backend'a
        - job_name: 'ui'
          static_configs:
          - targets: ['project-ui.dev.svc.cluster.local'] #ExternalIP ui
