---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "mongodb-exporter.fullname" . }}
  labels:
    app: crawler
    component: mongodb-exporter
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: crawler
    component: mongodb-exporter
    release: {{ .Release.Name }}