---
image:
  repository: achuprin/crawler-ui
  tag: latest

deployment:
  mongohost: mongodb.default.svc.cluster.local #internal ip монги
  mongoport: 27017
  flaskapp: ui.py

service:
  internalPort: 8000
  externalPort: 80

ingress:
  class: nginx